### ISSUE TITLE
Doesn't work after latest update[BUG]

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-fitbit#19]
**Describe the bug**
When you set the water and hunger it no longer pings you .

**To Reproduce**
1. Go to '...' Fitbit click your % and save. 
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
When you save your % it should make a sound and pop up in chat when you are around the % saved.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by GhzGarage** [comment]
Been updated again
